# Generated by Django 2.0.4 on 2018-04-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('usd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('eur', models.DecimalField(decimal_places=6, max_digits=12)),
                ('czk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('pln', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
    ]
