# Generated by Django 2.0.4 on 2018-04-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
